version: '2.26'
services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "5500:80" 
    networks:
      - closed_network

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "4000:4000"
    networks:
      - closed_network

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "3000:3000" 
    networks:
      - closed_network

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: Doctor
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3305:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - closed_network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    networks:
      - closed_network

networks:
  closed_network:

volumes:
  mysqldb:
