version: '2.3'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "30:80" 
    networks:
      - asgard

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    networks:
      - asgard

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - asgard

  db:
    image: mysql:latest
    ports:
      - "3400:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - asgard

networks:
  asgard:

volumes:
  db-data:
