version: '2.26'
services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    depends_on:
      - client
    networks:
      - closed_network

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      EMAIL_ID: "saiprashanth.cs21@bitsathy.ac.in"
      CLIENT_ID: "494572126295-g8ok8a5g0kvr3ceodj12h5orod5oe38v.apps.googleusercontent.com"
      CLIENT_SECRET: "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"
      REFERESH_TOKEN: "1//04lgPpCXy4viCCgYIARAAGAQSNwF-L9IrsqafbdGQns7DDzTRA885kyK4CXgK83o0bPG-XsgIGNPcSn0Jtul4xPT-XcOk19RYznw"
    volumes:
      - ./server:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - closed_network

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "3000:3000" 
    depends_on:
      - server
    networks:
      - closed_network

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: Doctor
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3305:3306" 
    volumes:
      - mysqldb:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

    networks:
      - closed_network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    networks:
      - closed_network

networks:
  closed_network:

volumes:
  mysqldb:
