version: '2.3'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "30:80" 
    networks:
      - asgard

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    networks:
      - asgard

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000" 
    networks:
      - asgard

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD:password
      - MYSQL_DATABASE:Doctor
    ports:
      - "3400:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - asgard

networks:
  asgard:

volumes:
  mysqldb:
    external: true
